version: "3.8"

services:
  mailcatcher:
    env_file:
      - .env
    build:
      context: .
      dockerfile: dockerfile.mailcatcher
      args:
        - IMAGE_TAG=${MAILCATCHER_IMAGE_TAG}
    container_name: goscrap_mailcatcher
    ports:
      - ${MAILCATCHER_EXTERNAL_PORT}:1080
      - "1025:1025"